### ISSUE TITLE
On select multiple rows on change font, my color and formatting dissapear

### ISSUE THREAD

**Issue by stefancvetkovic** [webfashionist/RichText#47] opened 2019-08-08 13:01 UTC
When I enter some text in multiple rows and select two or more lines and hit font size, those rows are converted to single one with default color and no fomratting options.

**Comment by webfashionist** [comment] 2024-01-05 00:02
This should be fixed since - I can not reproduce it anymore.
Please let me know if the bug still occurs.

**Closed by webfashionist** 2024-01-05 00:02 UTC
Labels: bug
