### ISSUE TITLE
Bug: unable to override the default colors

### ISSUE THREAD

**Issue by DotMG** [webfashionist/RichText#76] opened 2022-03-31 17:33 UTC
### Describe the problem

When initializing the richText object, if one wants another list of text colors, he would pass the new list as an array to the "colors" property of the object passed to richText constructor.
```
$("#rte").richText({
 colors: {'#000": 'black', '#999': 'grey'},
})
```
Or another expected way to change the default color : 
```
var defaultColors = []
defaultColors['#000'] = 'black';
defaultColors['#999'] = 'grey';
$('#rte').richText({
 colors: defaultColors,
})
```
But that does not change the default color list

### What did you expect?

With one of code above, I would expect to see only two colors when I click the colorpicker icon.

### What version and browser are you using?

Version: v.1.0.16
Browser and version: Tested on Firefox 78 and Firefox 98

### Reproducible test case

https://codepen.io/dotmg/pen/Exowgyd. Just click on the colorPicker icon, 

Forked to use Object.keys(settings.colors).length instead of settings.colors.length: 
https://codepen.io/dotmg/pen/vYpegLa

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the issue can be fixed when I do
- [x] I have [searched for existing issues](https://github.com/webfashionist/RichText/issues) and to the best of my knowledge this is not a duplicate
- [x] And I can provide a Pull Request : https://github.com/DotMG/RichText/commit/846a7501af43db70cc26d8855ff4c1dbb0e5bacf

**Comment by rpravisani** [comment] 2022-05-11 07:48
The problem is causes by the way the the script checks if there are any custom colors passed. The array woth custom colors should be an array with the hex color codes as key adn a description as value. The script then checks if length of the passed array is larger then 0, but Array.length always returns 0 in case the keys are not numerical.
I temporarily resolved the issue by changing the code in jquery.richtext.js from:

            if (settings.colors && settings.colors.length > 0) {
                colors = settings.colors;
            }

To:

            if (settings.colors) {
                colors = settings.colors;
            }

(line 1906 aprox in latest version)
For the minimized versione just search for `&&settings.colors.length>0` (it should appear just once) and delete it from the file.

Should be addressed in production version.

**Closed** 2023-06-29 01:42 UTC
