### ISSUE TITLE
bold, Italic and Under line not working

### ISSUE THREAD

**Issue by hussamdd** [webfashionist/RichText#9] opened 2017-11-20 11:55 UTC
For multiple rich text the bold, Italic and Under line not working

**Comment by webfashionist** [comment] 2017-11-20 23:47
Thank you for your report.

The issue is fixed with the commit c3c6548 and is already in the latest release [v.1.0.5](https://github.com/webfashionist/RichText/releases/tag/v.1.0.5)

Please keep me up to date if everything works (or doesn't) for you now

**Comment by Moworks** [comment] 2017-11-21 19:36
Thanks for fixing this, nice use of the Font Awesome icons

**Comment by webfashionist** [comment] 2017-11-23 23:52
Thank you, I'm glad you like it :)

**Closed by webfashionist** 2017-11-23 23:52 UTC
Labels: bug
